### ISSUE TITLE
关于特征融合后的residual units

### ISSUE THREAD

**Issue by yangyahu-1994** [gyyang23/AFPN#11]
![image](https://github.com/gyyang23/AFPN/assets/73293451/ad35f977-40b2-44f4-8567-667fc59004a3)
尊敬的作者：
       您好，论文中说特征融合后有4个residual units，每个residual unit包含2个3x3卷积，但是您给的[基于mmyolo实现的yolov5+PAFPN代码](https://github.com/gyyang23/AFPN/issues/6#issuecomment-1621982852)中，特征融合后有3个residual units
![image](https://github.com/gyyang23/AFPN/assets/73293451/727f9d63-599d-422a-94ca-8d093e8a4c9e)

![image](https://github.com/gyyang23/AFPN/assets/73293451/e5b3b2f2-9dc1-4742-b9e2-be9a2bae8bd1)

**Comment by gyyang23** [comment]
> ![image](https://user-images.githubusercontent.com/73293451/254458872-ad35f977-40b2-44f4-8567-667fc59004a3.png) 尊敬的作者： 您好，论文中说特征融合后有4个residual units，每个residual unit包含2个3x3卷积，但是您给的[基于mmyolo实现的yolov5+PAFPN代码](https://github.com/gyyang23/AFPN/issues/6#issuecomment-1621982852)中，特征融合后有3个residual units ![image](https://user-images.githubusercontent.com/73293451/254459813-727f9d63-599d-422a-94ca-8d093e8a4c9e.png)
> 
> ![image](https://user-images.githubusercontent.com/73293451/254460001-e5b3b2f2-9dc1-4742-b9e2-be9a2bae8bd1.png)

是这样的，论文后面部分我也提到了在yolo上是使用3个units。

**Comment by yangyahu-1994** [comment]
> > ![image](https://user-images.githubusercontent.com/73293451/254458872-ad35f977-40b2-44f4-8567-667fc59004a3.png) 尊敬的作者： 您好，论文中说特征融合后有4个residual units，每个residual unit包含2个3x3卷积，但是您给的[基于mmyolo实现的yolov5+PAFPN代码](https://github.com/gyyang23/AFPN/issues/6#issuecomment-1621982852)中，特征融合后有3个residual units ![image](https://user-images.githubusercontent.com/73293451/254459813-727f9d63-599d-422a-94ca-8d093e8a4c9e.png)
> > ![image](https://user-images.githubusercontent.com/73293451/254460001-e5b3b2f2-9dc1-4742-b9e2-be9a2bae8bd1.png)
> 
> 是这样的，论文后面部分我也提到了在yolo上是使用3个units。


好的，非常感谢作者。
