### ISSUE TITLE
请问下作者，您在训练yolo版本的AFPN时，前几个epoch精度大概是多少

### ISSUE THREAD

**Issue by NeKoooo233** [gyyang23/AFPN#14]
论文里是300个epoch才出结果吗

**Comment by gyyang23** [comment]
> 论文里是300个epoch才出结果吗

每隔10个epoch出一次结果。很久之前训练的，找不到训练日志了。你可以参考一下mmyolo的yolov5的训练日志。https://[download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739.log.json](https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739.log.json)

**Comment by NeKoooo233** [comment]
> > 论文里是300个epoch才出结果吗
> 
> 每隔10个epoch出一次结果。很久之前训练的，找不到训练日志了。你可以参考一下mmyolo的yolov5的训练日志。https://[download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739.log.json](https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739.log.json)

谢谢
