### ISSUE TITLE
关于特征融合后的残差单元数量问题

### ISSUE THREAD

**Issue by Shaw-Way** [gyyang23/AFPN#17]
作者，您好，您在论文中提到每次特征融合后使用四个残差单元学习特征，我想问一下，为什么是四个呢，您是否有实验过不同数量的残差单元对结果的影响

**Comment by gyyang23** [comment]
> 作者，您好，您在论文中提到每次特征融合后使用四个残差单元学习特征，我想问一下，为什么是四个呢，您是否有实验过不同数量的残差单元对结果的影响

你好，使用四个残差单元是通过消融实验得出的。

**Comment by Shaw-Way** [comment]
感谢回复
